# Generated by Django 3.2.8 on 2021-10-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('TweetId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Content', models.CharField(max_length=50)),
                ('DateInsert', models.DateTimeField()),
            ],
        ),
    ]
